### ISSUE TITLE
Player jump against a wall

### ISSUE THREAD

**Issue by jegankasi2** [BWRat/DES506_Oneiro#26] opened 2019-07-10 13:10 UTC
**Description:**
When the player character is against a wall and tries to jump the player does not jump. The player instead plays the push animation

**How many times can you reproduce this bug?**
Every time.

**What should the player be able to do?**
The player should be able to jump when against a collision and reach its maximum jump height

**Comment by BWRat** [comment] 2019-07-10 13:29
This is related to issue #27 and so will be assigned to the same programmer.  In both issues, this is caused by proximity-based pushing.

**Comment by cloneforum** [comment] 2019-07-17 15:18
is it still happening? I am waiting for @jegankasi2 to check if the issue is solved

**Comment by BWRat** [comment] 2019-07-25 09:46
I could not replicate the animation bug but have patched a fix for the jumping friction issue.  The player's collider now has a physics material that prevents friction between two colliders from preventing jump.

@jegankasi2 please test this and confirm whether or not it has worked.

**Comment by BWRat** [comment] 2019-07-25 10:08
@KeithorKeith has verified that this works.

**Closed by BWRat** 2019-07-25 10:08 UTC
Labels: Priority B
