### ISSUE TITLE
Push pull Object

### ISSUE THREAD

**Issue by jegankasi2** [BWRat/DES506_Oneiro#27] opened 2019-07-10 13:16 UTC
Not exactly a bug. In its current iteration the push pull object behaves differently.

**How does the push pull object in its current iteration work**
When the player moves against the movable object the player switches into the pushing animation and starts pushing the object automatically. The player must press button 'B' in order to hold the box and pull it

**How should the push pull object work**
The player must press the button 'B' in order to both push and pull the object. The player should not be able to contextually push the box without player input

**Comment by BWRat** [comment] 2019-07-10 13:29
This is related to issue #26 and so will be assigned to the same programmer.  In both issues, this is caused by proximity-based pushing.

**Comment by jegankasi2** [comment] 2019-07-18 13:53
Can the pull speed be the same as push speed

**Closed** 2019-07-19 14:38 UTC
Labels: Priority B
